"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Check, ChevronLeft, Clock3, Heart, MapPin, MessageCircle, Minus, Phone, Plus, ShoppingBag, Star, X } from "lucide-react";
import { RESTAURANT_INFO } from "@/data/restaurantInfo";
import { CATEGORIES, FOOD_IMAGES, MENU, type MenuItem } from "@/data/menuData";

type CartEntry = MenuItem & { selected: string; unitPrice: number; quantity: number };

const gallery = ["special", "maharaja", "momos", "noodles", "shake", "loaded"];

export default function Home() {
  const [category, setCategory] = useState("All");
  const [cart, setCart] = useState<CartEntry[]>([]);
  const [cartOpen, setCartOpen] = useState(false);
  const [checkoutOpen, setCheckoutOpen] = useState(false);
  const [selectedItem, setSelectedItem] = useState<MenuItem | null>(null);
  const [lightbox, setLightbox] = useState<string | null>(null);
  const [favorites, setFavorites] = useState<string[]>([]);
  const [customer, setCustomer] = useState({ name: "", address: "" });
  const [locationUrl, setLocationUrl] = useState("");
  const [locationStatus, setLocationStatus] = useState<"idle" | "loading" | "success" | "error">("idle");
  const isBrowsingAll = category === "All";
  const filtered = useMemo(() => MENU.filter((item) => category === "All" || item.category === category), [category]);
  const popular = MENU.filter((item) => item.featured);
  const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
  const subtotal = cart.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0);
  const deliveryCharge = subtotal > 0 && subtotal < 300 ? 50 : 0;
  const total = subtotal + deliveryCharge;
  const addToCart = (item: MenuItem, selected = item.options?.[0]?.label ?? "Regular", unitPrice = item.options?.[0]?.price ?? item.price) => {
    setCart((current) => { const existing = current.find((entry) => entry.id === item.id && entry.selected === selected); return existing ? current.map((entry) => entry === existing ? { ...entry, quantity: entry.quantity + 1 } : entry) : [...current, { ...item, selected, unitPrice, quantity: 1 }]; });
    setSelectedItem(null);
    setCartOpen(true);
  };
  const changeQuantity = (id: string, selected: string, amount: number) => setCart((current) => current.map((entry) => entry.id === id && entry.selected === selected ? { ...entry, quantity: entry.quantity + amount } : entry).filter((entry) => entry.quantity > 0));
  const toggleFavorite = (id: string) => setFavorites((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const requestCurrentLocation = () => {
    if (!navigator.geolocation) { setLocationStatus("error"); return; }
    setLocationStatus("loading");
    navigator.geolocation.getCurrentPosition((position) => {
      setLocationUrl(`https://www.google.com/maps?q=${position.coords.latitude},${position.coords.longitude}`);
      setLocationStatus("success");
    }, () => setLocationStatus("error"), { enableHighAccuracy: true, timeout: 10000, maximumAge: 300000 });
  };
  const sendWhatsApp = () => {
    const lines = cart.map((item) => `• ${item.quantity} x ${item.name} (${item.selected}) - Rs. ${item.unitPrice * item.quantity}`).join("\n");
    const message = `NEW ORDER - HONEY MONEY PIZZA CAFE\n\nCustomer: ${customer.name || "Guest"}\nDelivery: ${customer.address || "To be shared on WhatsApp"}\nCurrent location: ${locationUrl || "Location not shared"}\n\nITEMS\n${lines}\n\nTOTAL: Rs. ${total}\nPayment: Cash / UPI on Delivery`;
    window.open(`https://wa.me/${RESTAURANT_INFO.whatsapp}?text=${encodeURIComponent(message)}`, "_blank");
  };

  return <main className="app-shell">
    <nav className="app-nav"><a href="#home" className="brand"><span className="brand-mark">HM</span><span>HONEY MONEY<small>PIZZA CAFE</small></span></a><div className="desktop-nav"><a href="#home">Home</a><a href="#menu">Menu</a><a href="#combos">Combos</a><a href="#delivery">Delivery</a><a href="#about">About</a></div><div className="nav-actions"><a href={`tel:${RESTAURANT_INFO.phone}`} className="call-link"><Phone size={15} /> 76683 58422</a><button className="nav-order" onClick={() => setCartOpen(true)}><ShoppingBag size={16} /> Order <b>{totalItems}</b></button></div></nav>
    <section id="home" className="premium-hero"><div className="hero-content"><p className="kicker"><span /> 100% vegetarian · Dankaur & nearby campuses</p><h1>Good Food.<br /><span>Great Mood.</span></h1><p className="hero-lede">Freshly prepared pizzas, burgers, momos, noodles and shakes for your hostel, home or late-night study table.</p><div className="hero-ctas"><a href="#menu" className="primary-cta">Order something delicious <ArrowRight size={18} /></a><a href={`https://wa.me/${RESTAURANT_INFO.whatsapp}`} target="_blank" rel="noreferrer" className="ghost-cta"><MessageCircle size={18} /> WhatsApp us</a></div><div className="hero-proof"><span><Star size={15} fill="currentColor" /> Loved locally</span><span><Clock3 size={15} /> Open 24/7</span></div></div><div className="hero-visual"><div className="hero-glow" /><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><video className="hero-food-image hero-food-video" src="/gemini_generated_video_df37af96.mp4" autoPlay muted loop playsInline preload="auto" aria-label="Honey Money Pizza Cafe logo animation" /><span className="ingredient ingredient-one">🌶️</span><span className="ingredient ingredient-two">🧀</span><div className="hero-food-card"><span className="mini-tag">🔥 POPULAR NOW</span><strong>Honey Money Special</strong><small>Loaded toppings · Chef&apos;s pick</small><div><b>From Rs. 239</b><button onClick={() => addToCart(MENU[0])}><Plus size={15} /></button></div></div></div></section>
    <section className="category-bar"><div className="category-scroll">{CATEGORIES.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div></section>
    {isBrowsingAll && <section className="content-section popular-section"><div className="section-head"><div><p className="kicker">The repeat orders</p><h2>Popular Now</h2><p>The favourites people keep coming back for.</p></div><a href="#menu" className="view-link">View all <ArrowRight size={16} /></a></div><div className="popular-grid">{popular.map((item) => <FoodCard key={item.id} item={item} favorite={favorites.includes(item.id)} onFavorite={() => toggleFavorite(item.id)} onOpen={() => setSelectedItem(item)} />)}</div></section>}
    {isBrowsingAll && <section id="combos" className="content-section combo-section"><div className="section-head"><div><p className="kicker">More food, better value</p><h2>Made for sharing.</h2></div><a href="#menu" className="view-link">See menu <ArrowRight size={16} /></a></div><div className="combo-row">{MENU.filter((item) => item.category === "Combos").map((item, index) => <article className={`promo-card promo-${index + 1}`} key={item.id}><div><span className="mini-tag">COMBO 0{index + 1}</span><h3>{item.name}</h3><p>{item.description}</p><strong>Rs. {item.price}</strong><button onClick={() => addToCart(item)}>Order combo <Plus size={15} /></button></div><div className="promo-image" style={{ backgroundImage: `url(${FOOD_IMAGES[item.id] ?? FOOD_IMAGES.special})` }} /></article>)}<article className="promo-card promo-three"><div><span className="mini-tag">CROWD FAVOURITE</span><h3>Loaded Pizza</h3><p>Extra cheese, jalapeno, corn & mushroom.</p><strong>From Rs. 159</strong><button onClick={() => addToCart(MENU[2], "Medium", 319)}>Order pizza <Plus size={15} /></button></div><div className="promo-image" style={{ backgroundImage: `url(${FOOD_IMAGES.loaded})` }} /></article></div></section>}
    <section id="menu" className="content-section menu-section"><div className="section-head"><div><p className="kicker">Made fresh on order</p><h2>Pick your comfort.</h2><p>Real menu, real prices, zero fuss.</p></div></div><div className="menu-grid">{filtered.map((item) => <FoodCard key={item.id} item={item} favorite={favorites.includes(item.id)} onFavorite={() => toggleFavorite(item.id)} onOpen={() => setSelectedItem(item)} />)}</div>{filtered.length === 0 && <p className="empty-state">Nothing here yet. Try another craving.</p>}</section>
    <section id="delivery" className="delivery-map"><div className="map-copy"><p className="kicker">Local delivery, thoughtfully done</p><h2>We deliver<br /><span>around you.</span></h2><p>Dankaur, Noida International University, Supertech Upcountry, Gaur Yamuna City, Galgotias University and nearby hostels, PGs and residences.</p><div className="delivery-note"><strong>Free delivery on orders above Rs. 300</strong><small>Delivery charges may apply below the free-delivery threshold.</small></div><a href={RESTAURANT_INFO.googleMapsUrl} target="_blank" rel="noreferrer" className="ghost-cta"><MapPin size={17} /> Get cafe directions</a></div><div className="route-map"><span className="map-label label-niu">NIU <i /></span><span className="map-label label-galgotias">Galgotias <i /></span><span className="map-label label-dankaur">Dankaur <i /></span><span className="map-label label-hostels">Hostels & PGs <i /></span><span className="map-label label-supertech">Supertech <i /></span><span className="map-label label-gaur">Gaur Yamuna <i /></span><div className="route route-a" /><div className="route route-b" /><div className="route route-c" /><div className="map-center"><MapPin size={18} /></div></div></section>
    <section className="student-section"><div><p className="kicker">Between classes or after midnight</p><h2>Hungry between<br /><span>classes?</span></h2><p>From hostel cravings to evening snacks, get your favourites delivered around you.</p><a href="#menu" className="primary-cta">Order something delicious <ArrowRight size={17} /></a></div><div className="student-foods"><span>🍕<small>Pizza</small></span><span>🍔<small>Burger</small></span><span>🥟<small>Momos</small></span><span>🍜<small>Noodles</small></span><span>🥤<small>Shakes</small></span></div></section>
    <section className="content-section gallery-section"><div className="section-head"><div><p className="kicker">A little visual proof</p><h2>Made to be shared.</h2></div><a href={`https://wa.me/${RESTAURANT_INFO.whatsapp}`} target="_blank" rel="noreferrer" className="view-link">Order now <ArrowRight size={16} /></a></div><div className="gallery-grid">{gallery.map((id) => <button key={id} className={`gallery-item gallery-${id}`} onClick={() => setLightbox(id)} style={{ backgroundImage: `url(${FOOD_IMAGES[id] ?? FOOD_IMAGES.special})` }}><span>{MENU.find((item) => item.id === id)?.name}</span></button>)}</div></section>
    <section id="about" className="about-section"><div className="about-visual" style={{ backgroundImage: `url(${FOOD_IMAGES.garlic})` }}><span>LOCAL<br />FOOD</span></div><div><p className="kicker">Our little corner of Dankaur</p><h2>Local food.<br /><span>Made for local cravings.</span></h2><p>Honey Money Pizza Cafe is a warm neighbourhood kitchen in Patpara Gali, serving the local Dankaur and nearby university community with honest vegetarian comfort food.</p><div className="about-list"><span><Check size={15} /> Freshly prepared on order</span><span><Check size={15} /> Pocket-friendly prices</span><span><Check size={15} /> Direct WhatsApp ordering</span></div></div></section>
    <section className="final-cta"><p className="kicker">Your next favourite meal is close</p><h2>Craving something?</h2><p>One tap, one delicious decision.</p><div><a href={`https://wa.me/${RESTAURANT_INFO.whatsapp}`} target="_blank" rel="noreferrer" className="primary-cta"><MessageCircle size={17} /> Order on WhatsApp</a><a href={`tel:${RESTAURANT_INFO.phone}`} className="ghost-cta"><Phone size={17} /> Call now</a><a href={RESTAURANT_INFO.googleMapsUrl} target="_blank" rel="noreferrer" className="ghost-cta"><MapPin size={17} /> Get directions</a></div></section>
    <footer><a href="#home" className="brand"><span className="brand-mark">HM</span><span>HONEY MONEY<small>PIZZA CAFE</small></span></a><div><strong>Explore</strong><a href="#menu">Menu</a><a href="#combos">Combos</a><a href="#about">About</a></div><div><strong>Find us</strong><p>{RESTAURANT_INFO.address}<br />{RESTAURANT_INFO.city}</p></div><div><strong>Order directly</strong><a href={`tel:${RESTAURANT_INFO.phone}`}>76683 58422</a><p>Open 24/7</p></div></footer>
    <nav className="mobile-nav"><a href="#home">⌂<small>Home</small></a><a href="#menu">⌕<small>Menu</small></a><a href="#combos">✦<small>Offers</small></a><button onClick={() => setCartOpen(true)}><ShoppingBag size={18} /><small>Cart {totalItems ? `(${totalItems})` : ""}</small></button></nav>
    {totalItems > 0 && <button className="floating-cart" onClick={() => setCartOpen(true)}><span><ShoppingBag size={18} /> {totalItems} items</span><b>Rs. {total}</b><ArrowRight size={18} /></button>}
    {selectedItem && <FoodModal item={selectedItem} onClose={() => setSelectedItem(null)} onAdd={addToCart} />}
    {cartOpen && <CartDrawer cart={cart} subtotal={subtotal} deliveryCharge={deliveryCharge} total={total} totalItems={totalItems} onClose={() => setCartOpen(false)} onChange={changeQuantity} onCheckout={() => { setCheckoutOpen(true); requestCurrentLocation(); }} />}
    {checkoutOpen && <div className="modal-backdrop checkout-overlay"><div className="checkout-modal"><button className="close-button" onClick={() => setCheckoutOpen(false)} aria-label="Close checkout"><X size={20} /></button><p className="kicker">Almost there</p><h2>Where should we bring it?</h2><p>We&apos;ll open WhatsApp with your address and current location link.</p><input value={customer.name} onChange={(event) => setCustomer({ ...customer, name: event.target.value })} placeholder="Your name / room number" /><input value={customer.address} onChange={(event) => setCustomer({ ...customer, address: event.target.value })} placeholder="Hostel, landmark or delivery address" /><button className={`location-button location-${locationStatus}`} onClick={requestCurrentLocation} disabled={locationStatus === "loading"}><MapPin size={17} /> {locationStatus === "loading" ? "Getting your location..." : locationStatus === "success" ? "Location captured" : locationStatus === "error" ? "Retry current location" : "Use my current location"}</button><small className="location-help">Your browser will ask for location permission. This is shared only in the WhatsApp order.</small><button className="whatsapp-button" onClick={sendWhatsApp}><MessageCircle size={18} /> Place order on WhatsApp</button></div></div>}
    {lightbox && <div className="modal-backdrop lightbox" onClick={() => setLightbox(null)}><button className="close-button" onClick={() => setLightbox(null)} aria-label="Close image"><X size={22} /></button><div className="lightbox-image" style={{ backgroundImage: `url(${FOOD_IMAGES[lightbox]})` }} onClick={(event) => event.stopPropagation()} /><strong>{MENU.find((item) => item.id === lightbox)?.name}</strong></div>}
  </main>;
}

function FoodCard({ item, favorite, onFavorite, onOpen }: { item: MenuItem; favorite: boolean; onFavorite: () => void; onOpen: () => void }) {
  return <article className="food-card" onClick={onOpen}><div className="card-image" style={{ backgroundImage: `url(${FOOD_IMAGES[item.id] ?? FOOD_IMAGES.special})` }}><button className={`favorite-button ${favorite ? "liked" : ""}`} onClick={(event) => { event.stopPropagation(); onFavorite(); }} aria-label="Toggle favorite"><Heart size={17} fill={favorite ? "currentColor" : "none"} /></button>{item.featured && <span className="card-badge">Popular</span>}</div><div className="card-body"><div className="card-title"><h3>{item.name}</h3><span className="veg-dot" /></div><p>{item.description}</p><div className="card-footer"><strong>Rs. {item.price}</strong><button className="quick-add" onClick={(event) => { event.stopPropagation(); onOpen(); }}><Plus size={17} /></button></div></div></article>;
}

function FoodModal({ item, onClose, onAdd }: { item: MenuItem; onClose: () => void; onAdd: (item: MenuItem, selected?: string, price?: number) => void }) {
  const [selected, setSelected] = useState(item.options?.[0]);
  const [quantity, setQuantity] = useState(1);
  const price = selected?.price ?? item.price;
  return <div className="modal-backdrop" onClick={onClose}><div className="food-modal" onClick={(event) => event.stopPropagation()}><button className="close-button" onClick={onClose} aria-label="Close details"><ChevronLeft size={22} /></button><button className="modal-heart" aria-label="Favorite"><Heart size={19} /></button><div className="modal-food-image" style={{ backgroundImage: `url(${FOOD_IMAGES[item.id] ?? FOOD_IMAGES.special})` }} /><div className="modal-details"><span className="mini-tag">{item.featured ? "🔥 POPULAR" : "100% VEGETARIAN"}</span><h2>{item.name}</h2><div className="rating"><Star size={15} fill="currentColor" /> 4.9 <span>Freshly prepared for you</span></div><p>{item.description}</p>{item.options && <><h4>Choose your portion</h4><div className="modal-options">{item.options.map((option) => <button key={option.label} className={selected?.label === option.label ? "selected" : ""} onClick={() => setSelected(option)}>{option.label}<small>Rs. {option.price}</small></button>)}</div></>}<div className="modal-bottom"><div className="quantity"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={15} /></button><b>{quantity}</b><button onClick={() => setQuantity(quantity + 1)}><Plus size={15} /></button></div><button className="modal-add" onClick={() => { for (let index = 0; index < quantity; index += 1) onAdd(item, selected?.label, price); }}>Add to cart <strong>Rs. {price * quantity}</strong></button></div></div></div></div>;
}

function CartDrawer({ cart, subtotal, deliveryCharge, total, totalItems, onClose, onChange, onCheckout }: { cart: CartEntry[]; subtotal: number; deliveryCharge: number; total: number; totalItems: number; onClose: () => void; onChange: (id: string, option: string, amount: number) => void; onCheckout: () => void }) {
  return <div className="modal-backdrop cart-backdrop" onClick={onClose}><aside className="cart-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-head"><div><p className="kicker">Your order</p><h2>Cart <span>({totalItems})</span></h2></div><button className="close-button" onClick={onClose} aria-label="Close cart"><X size={20} /></button></div>{cart.length === 0 ? <div className="empty-cart"><ShoppingBag size={31} /><p>Your cart is waiting for something delicious.</p></div> : <><div className="cart-lines">{cart.map((item) => <div className="cart-line" key={`${item.id}-${item.selected}`}><div className="line-thumb" style={{ backgroundImage: `url(${FOOD_IMAGES[item.id] ?? FOOD_IMAGES.special})` }} /><div className="line-info"><strong>{item.name}</strong><small>{item.selected} · Rs. {item.unitPrice}</small><div className="quantity"><button onClick={() => onChange(item.id, item.selected, -1)}><Minus size={13} /></button><b>{item.quantity}</b><button onClick={() => onChange(item.id, item.selected, 1)}><Plus size={13} /></button></div></div><strong className="line-price">Rs. {item.unitPrice * item.quantity}</strong></div>)}</div><div className="delivery-status">{deliveryCharge === 0 ? <><strong>You are eligible for free delivery</strong><small>Free delivery on orders of Rs. 300 or more</small></> : <><span>Delivery charge</span><strong>Rs. 50</strong><small>Add Rs. {300 - subtotal} more for free delivery</small></>}</div><div className="cart-total"><span>Subtotal</span><strong>Rs. {subtotal}</strong></div><div className="cart-total"><span>Total</span><strong>Rs. {total}</strong></div><button className="primary-cta checkout-button" onClick={onCheckout}>Continue to checkout <ArrowRight size={17} /></button></>}</aside></div>;
}